name: Enhancement
description: Create a User Story
title: "[User Story]: "
labels: ["enhancement"]
assignees:
  - thisisbramiller
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: user-story
    attributes:
      label: User Story
      description: As a < WHO >, I want < WHAT > so that < WHY >.
      placeholder: ex. As a developer, I want to set up my local development environment, so that I can start working on the proof of concept web app.
    validations:
      required: true
  - type: dropdown
    id: estimate
    attributes:
      label: Estimation of effort
      options:
        - 30 minutes
        - 1 hour
        - 2 hours
        - 3 hours
        - 4 hours
        - 5 hours
        - 6 hours
        - 7 hours
        - 1 day
        - 2 days
        - 3 days
        - 4 days
        - 5 days
        - 1 week
        - 6 days
        - 7 days
        - 8 days
        - 9 days
        - 10 days
        - 2 weeks
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
    validations:
      required: true
  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
    validations:
      required: true
